// Copyright 2009, Google Inc. All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
//  1. Redistributions of source code must retain the above copyright notice,
//     this list of conditions and the following disclaimer.
//  2. Redistributions in binary form must reproduce the above copyright notice,
//     this list of conditions and the following disclaimer in the documentation
//     and/or other materials provided with the distribution.
//  3. Neither the name of Google Inc. nor the names of its contributors may be
//     used to endorse or promote products derived from this software without
//     specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED
// WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
// MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
// EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
// OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
// WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
// OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
// ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#include "kml/dom/visitor.h"

#include "kml/dom/kmldom.h"
#include "kml/dom/kml_cast.h"

namespace kmldom {

Visitor::Status Visitor::VisitElement(const ElementPtr& node) {
  return CONTINUE;
}
void Visitor::VisitElementEnd(const ElementPtr& node) {
  /* do nothing */
}

// >> Visitor API Start >>
// Autogenerated code to implement the visitor pattern.
Visitor::Status Visitor::VisitContainer(
    const ContainerPtr& element) {
  return VisitFeature(element);
}
void Visitor::VisitContainerEnd(
    const ContainerPtr& element) {
  VisitFeatureEnd(element);
}

Visitor::Status Visitor::VisitDocument(
    const DocumentPtr& element) {
  return VisitContainer(element);
}
void Visitor::VisitDocumentEnd(
    const DocumentPtr& element) {
  VisitContainerEnd(element);
}

Visitor::Status Visitor::VisitFeature(
    const FeaturePtr& element) {
  return VisitObject(element);
}
void Visitor::VisitFeatureEnd(
    const FeaturePtr& element) {
  VisitObjectEnd(element);
}

Visitor::Status Visitor::VisitFolder(
    const FolderPtr& element) {
  return VisitContainer(element);
}
void Visitor::VisitFolderEnd(
    const FolderPtr& element) {
  VisitContainerEnd(element);
}

Visitor::Status Visitor::VisitGroundOverlay(
    const GroundOverlayPtr& element) {
  return VisitOverlay(element);
}
void Visitor::VisitGroundOverlayEnd(
    const GroundOverlayPtr& element) {
  VisitOverlayEnd(element);
}

Visitor::Status Visitor::VisitKml(
    const KmlPtr& element) {
  return VisitElement(element);
}
void Visitor::VisitKmlEnd(
    const KmlPtr& element) {
  VisitElementEnd(element);
}

Visitor::Status Visitor::VisitObject(
    const ObjectPtr& element) {
  return VisitElement(element);
}
void Visitor::VisitObjectEnd(
    const ObjectPtr& element) {
  VisitElementEnd(element);
}

Visitor::Status Visitor::VisitOverlay(
    const OverlayPtr& element) {
  return VisitFeature(element);
}
void Visitor::VisitOverlayEnd(
    const OverlayPtr& element) {
  VisitFeatureEnd(element);
}

Visitor::Status Visitor::VisitPhotoOverlay(
    const PhotoOverlayPtr& element) {
  return VisitOverlay(element);
}
void Visitor::VisitPhotoOverlayEnd(
    const PhotoOverlayPtr& element) {
  VisitOverlayEnd(element);
}

Visitor::Status Visitor::VisitPlacemark(
    const PlacemarkPtr& element) {
  return VisitFeature(element);
}
void Visitor::VisitPlacemarkEnd(
    const PlacemarkPtr& element) {
  VisitFeatureEnd(element);
}

Visitor::Status Visitor::VisitScreenOverlay(
    const ScreenOverlayPtr& element) {
  return VisitOverlay(element);
}
void Visitor::VisitScreenOverlayEnd(
    const ScreenOverlayPtr& element) {
  VisitOverlayEnd(element);
}
// << Visitor API End <<

}  // end namespace kmldom
