# Copyright 2008, Google Inc. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without 
# modification, are permitted provided that the following conditions are met:
#
#  1. Redistributions of source code must retain the above copyright notice, 
#     this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright notice,
#     this list of conditions and the following disclaimer in the documentation
#     and/or other materials provided with the distribution.
#  3. Neither the name of Google Inc. nor the names of its contributors may be
#     used to endorse or promote products derived from this software without
#     specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF 
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
# EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, 
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR 
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF 
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

import os.path

Import('env')
env = env.Clone()

env.Append(CPPPATH=['#/third_party/zlib-1.2.3/contrib'])

kmlutil_header_files = [
  'fileio.h',
  'kmz.h',
  'unit_test.h',
  'util.h',
]

kmlutil_cc_files = [
  'fileio.cc',
  'kmz.cc',
]

# Library is static.
kmlutil = env.Library(target='kmlutil', source=kmlutil_cc_files)
AlwaysBuild(kmlutil)  # so examples will work

# Installation.
env.Install(env['LIBDIR'], kmlutil)
env.Install(os.path.join(env['INCDIR'], 'kml', 'util'), kmlutil_header_files)

# Unit Tests
env.Append(LIBS=['kmlutil', 'minizip', env['LIBZ']])
env.Append(LIBPATH=['#/build/kml/util'])
env.UnitTest('kmz_test', 'kmz_test.cc')
