find_package(ZLIB)
mark_as_advanced(ZLIB_INCLUDE_DIR)
mark_as_advanced(ZLIB_LIBRARY)
if(ZLIB_FOUND)
  set(HAVE_SYSTEM_ZLIB TRUE)
  set(ZLIB_LIBRARY ${ZLIB_LIBRARIES})
else()
  set(HAVE_SYSTEM_ZLIB FALSE)
endif()